benchmark: 'dmc'

param:
  domain_name: 'humanoid'
  task_name: 'run'

  visualize_reward: false
  from_pixels: false
  height: 84
  width: 84
  camera_id: 0
  frame_skip: 1
  episode_length: 1000
  environment_kwargs: null
  time_limit: null
  channels_first: true
