defaults:
  - agent: sac
  - env: gym
  - _self_

seed: 1
device: 'cuda:0'
total_steps: 10_000_000

wandb_cfg:
  use_wandb_log: True
  entity: 'grandpadzb'

Trainer:
  _target_: train.Trainer
  exploration_steps: 5_000
  eval_interval: 500_000
  log_interval: 5_000
  save_interval: 500_000
  target_update_interval: 2
  gradient_step_interval: 2
  n_gradient_steps: 1
  save_video: True
  no_terminal: True


